name: Continuous Integration

on:
  push:
    branches: [ huvudgrenen ]    
    paths:
      - 'Liber.Onlinebok.Client/**'
      - 'Liber.Onlinebok.Client.Tests/**'
      - '.github/**'
  pull_request:
    branches: [ huvudgrenen ]
    paths:     
      - 'Liber.Onlinebok.Client/**'
      - 'Liber.Onlinebok.Client.Tests/**'
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Create tag dry run
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        
    - name: Create version
      id: version
      run: |
        version=$(echo ${{ steps.tag_version.outputs.new_tag }} | cut -c2-)
        echo "::set-output name=version::$version"
      shell: bash
        
    - name: SemVer suffix
      id: semver
      uses: mikaeldui/actions/nupkg/semver-suffix@main
      with:
        default_branch: huvudgrenen
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${{ steps.version.outputs.version }}${{ steps.semver.outputs.suffix }}
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

      # Pack & Publish
      
    - name: 'Pack & Publish Artifact'
      uses: mikaeldui/actions/nupkg/dotnet/pack-and-publish-artifact@main
      with:
        version: ${{ steps.version.outputs.version }}${{ steps.semver.outputs.suffix }}
        project_directory: ./Liber.Onlinebok.Client
        
  nuget-org:
    name: 'NuGet.org'
    if: ${{ (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'pull_request' || (startsWith(github.ref, 'refs/heads/features') && github.event_name == 'push') }}
    uses: mikaeldui/actions/.github/workflows/nuget.org-deploy.yml@main
    needs: build
    secrets:
      NUGET_ORG_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}

  github-packages:
    name: 'GitHub Packages'
    if: ${{ (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'pull_request' || (startsWith(github.ref, 'refs/heads/features') && github.event_name == 'push') }}
    uses: mikaeldui/actions/.github/workflows/github-packages-deploy.yml@main
    needs: build

  github-release:
    name: 'GitHub Release'
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    uses: mikaeldui/actions/.github/workflows/github-release.yml@main
    needs: [nuget-org, github-packages]
    with:
      github_packages_url: ${{ needs.github-packages.outputs.url }}
      nuget_org_url: ${{ needs.nuget-org.outputs.url }}
